swagger: "2.0"

info:
  title: "Redis High Scores Leaderboard"
  version: "1.0"
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# Added by API Auto Mocking Plugin

basePath: /v1.0


schemes:
 - https
 - http
# tags are used for organizing operations
tags:
- name: public
  description: Operations available to regular developers
- name: admins
  description: Secured Admin-only calls




paths:
  
  /todays-champion/:
    get:
      operationId: api.scores.getTodaysCurrentChampion
      responses:
        '200':
          description: 'The top user and their score'
  /today-leaderboard/:
    get:
      operationId: api.scores.getLeaderboard
      responses:
        '200':
          description: 'List of high scorers'

  /logscore/:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: productPayload
        description: Device ID and score 
        schema:
          $ref: '#/definitions/Score'
      operationId: api.scores.setPlayerScore
      responses:
        201:
          description: Successfully added product to the DB
        400:
          description: invalid input, object invalid
        409:
          description: an existing item already exists

definitions:
  Score:
    type: object
    properties:
      userid: { type: string }
      score: { type: string }
  
  